#!/bin/bash
set -e
shopt -s extglob
source ${PG_APP_HOME}/env-defaults

PG_CONF=${PG_DATADIR}/postgresql.conf
PG_HBA_CONF=${PG_DATADIR}/pg_hba.conf
PG_IDENT_CONF=${PG_DATADIR}/pg_ident.conf
PG_RECOVERY_CONF=${PG_DATADIR}/recovery.conf
reset="\033[0m"
yellow="\033[38;5;178m"
yellow_bold="\033[38;5;226m"
red="\033[91m"
orange="\033[38;5;208m"
regular=""


file_env() {
  local var="$1"
  local fileVar="${var}_FILE"
  local def="${2:-}"
  if [ "${!var:-}" ] && [ "${!fileVar:-}" ]; then
      echo >&2 "error: both $var and $fileVar are set (but are exclusive)"
      exit 1
  fi
  local val="$def"
  if [ "${!var:-}" ]; then
      val="${!var}"
  elif [ "${!fileVar:-}" ]; then
      val="$(< "${!fileVar}")"
  fi
  export "$var"="$val"
  unset "$fileVar"
}

file_env 'POSTGRES_INITDB_ARGS'
file_env 'POSTGRES_PASSWORD'

# Compatibility layer with the official postgres image
if [[ ! -z "$PGUSER" ]]; then
  # Official image uses this user for command line tools, e.g.
  # PGUSER="${PGUSER:-postgres}" pg_ctl -D "$PGDATA" -m fast -w stop
  # PGUSER is the POSTGRES user used with these tools
  # our PG_USER, however, is the system account that's used for logging in.
  echo -e "${orange}‣ Compatility warning: ${yellow}this image always uses ${yellow_bold}postgres${yellow} for ${yellow_bold}PG_USER${yellow}. Ignoring setting.${reset}"
  # PGUSER="${PGUSER:-postgres}"
fi

if [[ ! -z "$POSTGRES_USER" ]]; then
  echo -e "${orange}‣ Compatility layer: setting DB_USER to: ${yellow_bold}'$POSTGRES_USER'${yellow} from ${yellow_bold}POSTGRES_USER${reset}"
  DB_USER="$POSTGRES_USER"
fi

if [[ ! -z "$POSTGRES_PASSWORD" ]]; then
  echo -e "${orange}‣ Compatility layer: setting DB_PASS from ${yellow_bold}POSTGRES_PASSWORD${reset}"
  DB_PASS="$POSTGRES_PASSWORD"
fi


if [[ ! -z "$POSTGRES_DB" ]]; then
  echo -e "${orange}‣ Compatility layer: setting DB_NAME to: ${yellow_bold}'$POSTGRES_DB'${yellow} from ${yellow_bold}POSTGRES_DB${reset}"
  DB_NAME="$POSTGRES_DB"
fi

## Execute command as PG_USER
exec_as_postgres() {
  su-exec postgres "$@"
}

map_uidgid() {
  USERMAP_ORIG_UID=$(id -u ${PG_USER})
  USERMAP_ORIG_GID=$(id -g ${PG_USER})
  USERMAP_GID=${USERMAP_GID:-${USERMAP_UID:-$USERMAP_ORIG_GID}}
  USERMAP_UID=${USERMAP_UID:-$USERMAP_ORIG_UID}
  if [[ ${USERMAP_UID} != ${USERMAP_ORIG_UID} ]] || [[ ${USERMAP_GID} != ${USERMAP_ORIG_GID} ]]; then
    echo "Adapting uid and gid for ${PG_USER}:${PG_USER} to $USERMAP_UID:$USERMAP_GID"
    groupmod -o -g ${USERMAP_GID} ${PG_USER}
    sed -i -e "s|:${USERMAP_ORIG_UID}:${USERMAP_GID}:|:${USERMAP_UID}:${USERMAP_GID}:|" /etc/passwd
  fi
}

create_datadir() {
  mkdir -p ${PG_HOME}
  echo "Initializing data: ${PG_DATADIR}"
  if [[ -d ${PG_DATADIR} ]]; then
    echo "...setting permissions on files ${PG_DATADIR}"
    find ${PG_DATADIR} -type f -exec chmod 0600 {} \;
    find ${PG_DATADIR} -type d -exec chmod 0700 {} \;
  fi
  echo "...reowning ${PG_DATADIR} to ${PG_USER}:${PG_USER}"
  chown -R ${PG_USER}:${PG_USER} ${PG_HOME}
}

create_certdir() {
  echo "Initializing certs: ${PG_CERTDIR}"
  mkdir -p ${PG_CERTDIR}
  [[ -f ${PG_CERTDIR}/server.crt ]] && chmod 0644 ${PG_CERTDIR}/server.crt
  [[ -f ${PG_CERTDIR}/server.key ]] && chmod 0640 ${PG_CERTDIR}/server.key
  chmod 0755 ${PG_CERTDIR}
  chown -R root:${PG_USER} ${PG_CERTDIR}
}

create_logdir() {
  echo "Initializing logs: ${PG_LOGDIR}"
  mkdir -p ${PG_LOGDIR}
  chmod -R 1775 ${PG_LOGDIR}
  chown -R root:${PG_USER} ${PG_LOGDIR}
}

create_rundir() {
  echo "Initializing run: ${PG_RUNDIR}"
  mkdir -p ${PG_RUNDIR} ${PG_RUNDIR}/${PG_VERSION}-main.pg_stat_tmp
  chmod -R 0755 ${PG_RUNDIR}
  chmod g+s ${PG_RUNDIR}
  chown -R ${PG_USER}:${PG_USER} ${PG_RUNDIR}
}

set_postgresql_param() {
  local key=${1}
  local value=${2}
  local verbosity=${3:-verbose}

  if [[ -n ${value} ]]; then
    local current=$(exec_as_postgres sed -n -e "s/^\(${key} = '\)\([^ ']*\)\(.*\)$/\2/p" ${PG_CONF})
    if [[ "${current}" != "${value}" ]]; then
      if [[ ${verbosity} == verbose ]]; then
        echo -e "${yellow}‣ Setting postgresql.conf parameter: ${yellow_bold}${key} = '${value}'${reset}"
      fi
      value="$(echo "${value}" | sed 's|[@]|\\@|g')"
      exec_as_postgres sed -r -i "s@^[#]*[ ]*${key} = .*@${key} = '${value}'@" ${PG_CONF}
    fi
  fi
}

set_recovery_param() {
  local key=${1}
  local value=${2}
  local hide=${3}
  if [[ -n ${value} ]]; then
    local current=$(exec_as_postgres sed -n -e "s/^\(.*\)\(${key}=\)\([^ ']*\)\(.*\)$/\3/p" ${PG_RECOVERY_CONF})
    if [[ "${current}" != "${value}" ]]; then
      case ${hide} in
        true)  echo -e "${yellow}‣ Setting primary_conninfo parameter: ${key}${reset}" ;;
        *) echo -e "${yellow}‣ Setting primary_conninfo parameter: ${key} = '${value}'${reset}" ;;
      esac
      exec_as_postgres sed -i "s|${key}=[^ ']*|${key}=${value}|" ${PG_RECOVERY_CONF}
    fi
  fi
}

set_hba_param() {
  local value=${1}
  if ! grep -q "$(sed "s| | \\\+|g" <<< ${value})" ${PG_HBA_CONF}; then
    echo "${value}" >> ${PG_HBA_CONF}
  fi
}

configure_ssl() {
  ## NOT SURE IF THIS IS A GOOD ALTERNATIVE TO ENABLE SSL SUPPORT BY DEFAULT ##
  ## BECAUSE USERS WHO PULL A PREBUILT IMAGE WILL HAVE THE SAME CERTIFICATES ##
  # if [[ ! -f ${PG_CERTDIR}/server.crt && ! -f ${PG_CERTDIR}/server.key ]]; then
  #   if [[ -f /etc/ssl/certs/ssl-cert-snakeoil.pem && -f /etc/ssl/private/ssl-cert-snakeoil.key ]]; then
  #     ln -sf /etc/ssl/certs/ssl-cert-snakeoil.pem ${PG_CERTDIR}/server.crt
  #     ln -sf /etc/ssl/private/ssl-cert-snakeoil.key ${PG_CERTDIR}/server.key
  #   fi
  # fi

  if [[ -f ${PG_CERTDIR}/server.crt && -f ${PG_CERTDIR}/server.key ]]; then
    PG_SSL=${PG_SSL:-on}
    set_postgresql_param "ssl_cert_file" "${PG_CERTDIR}/server.crt"
    set_postgresql_param "ssl_key_file" "${PG_CERTDIR}/server.key"
  fi
  PG_SSL=${PG_SSL:-off}
  set_postgresql_param "ssl" "${PG_SSL}"
}

configure_hot_standby() {
  if [[ ${PG_LOG_ARCHIVING} ]]; then
    echo "PG_LOG_ARCHIVING enabled; configuring standby..."

    case ${REPLICATION_MODE} in
      slave|snapshot|backup)
        echo "REPLICATION_MODE=${REPLICATION_MODE}; wal_level = minimal, hot_standby = on..."

        set_postgresql_param "wal_level" "minimal"
        set_postgresql_param "hot_standby" "on"
        set_postgresql_param "max_wal_senders" "0"
        ;;
      *)
        echo "Configuring master for WAL archiving..."
        set_postgresql_param "wal_level" "replica"
        set_postgresql_param "max_wal_senders" "16"
        set_postgresql_param "checkpoint_segments" "8"
        set_postgresql_param "wal_keep_segments" "32"
        # Specifies whether or not you can connect and run queries during recovery, as described in Section 25.5.
        # The default value is off. This parameter can only be set at server start.
        # It only has effect during archive recovery or in standby mode.
        set_postgresql_param "hot_standby" "on"
        ;;
    esac
  else
    echo "PG_LOG_ARCHIVING not configured; wal_level = minimal, hot_standby = off..."
    set_postgresql_param "max_wal_senders" "0"
    set_postgresql_param "wal_level" "minimal"
    set_postgresql_param "hot_standby" "off"
  fi
}

configure_log_archiving() {
  if [[ ! -z ${PG_LOG_ARCHIVING} ]]; then
    echo "Enabling log archiving..."
    set_postgresql_param "archive_mode" "on"

    # This will return true if a variable is unset or set to the empty string ("").
    if [[ ! -z ${PG_LOG_ARCHIVING_COMMAND} ]]; then
      echo "Using default log archiving system..."
      log_archive="${PG_HOME}/wal-backup/"
      mkdir -p ${log_archive}
      backup_in_progress="test \! -f ${log_archive}/backup_in_progress"
      file_exists="test -f ${log_archive}/%f"
      copy_file="cp %p ${log_archive}/%f"
      execute_shell="[[ \! -x ${log_archive}/archive.sh ]] || ([[ -x ${log_archive}/archive.sh ]] && ${log_archive}/archive.sh %f %p)"
      set_postgresql_param "archive_command" "(${backup_in_progress} || (${file_exists} || (${copy_file} && (${execute_shell}))))"
    else
      echo -e "${yellow}‣ Using custom log archiving command: ${yellow_bold}${PG_LOG_ARCHIVING_COMMAND}${reset}"
      set_postgresql_param "archive_command" "${PG_LOG_ARCHIVING_COMMAND}"
    fi
  else
    echo -e "${yellow}‣ Disabling log archiving${reset}"
    set_postgresql_param "archive_mode" "off"
  fi
}

initialize_database() {
  if [[ ! -f ${PG_DATADIR}/PG_VERSION ]]; then
    case ${REPLICATION_MODE} in
      slave|snapshot|backup)
        if [[ -z $REPLICATION_HOST ]]; then
          echo "ERROR! Cannot continue without the REPLICATION_HOST. Exiting..."
          exit 1
        fi

        if [[ -z $REPLICATION_USER ]]; then
          echo "ERROR! Cannot continue without the REPLICATION_USER. Exiting..."
          exit 1
        fi

        if [[ -z $REPLICATION_PASS ]]; then
          echo "ERROR! Cannot continue without the REPLICATION_PASS. Exiting..."
          exit 1
        fi

        echo -n "Waiting for $REPLICATION_HOST to accept connections (60s timeout)"
        timeout=60
        while ! ${PG_BINDIR}/pg_isready -h $REPLICATION_HOST -p $REPLICATION_PORT -t 1 >/dev/null 2>&1
        do
          timeout=$(expr $timeout - 1)
          if [[ $timeout -eq 0 ]]; then
            echo "Timeout! Exiting..."
            exit 1
          fi
          echo -n "."
          sleep 1
        done
        echo

        case ${REPLICATION_MODE} in
          slave)
            echo "Replicating initial data from $REPLICATION_HOST..."
            export PGPASSWORD=$REPLICATION_PASS
            exec_as_postgres ${PG_BINDIR}/pg_basebackup -D ${PG_DATADIR} \
              -h ${REPLICATION_HOST} -p ${REPLICATION_PORT} -U ${REPLICATION_USER} -X stream -w >/dev/null
            ;;
          snapshot)
            echo "Generating a snapshot data on $REPLICATION_HOST..."
            export PGPASSWORD=$REPLICATION_PASS
            exec_as_postgres ${PG_BINDIR}/pg_basebackup -D ${PG_DATADIR} \
              -h ${REPLICATION_HOST} -p ${REPLICATION_PORT} -U ${REPLICATION_USER} -X fetch -w >/dev/null
            ;;
          backup)
            echo "Backing up data on $REPLICATION_HOST..."
            export PGPASSWORD=$REPLICATION_PASS
            exec_as_postgres ${PG_BINDIR}/pg_basebackup -D ${PG_DATADIR} \
              -h ${REPLICATION_HOST} -p ${REPLICATION_PORT} -U ${REPLICATION_USER} -X fetch -w >/dev/null
            exit 0
            ;;
        esac
        ;;
      *)
        echo "Initializing database..."
        PG_OLD_VERSION=$(find ${PG_HOME}/+([0-9])?(.[0-9])/main -maxdepth 1 -name PG_VERSION 2>/dev/null | grep -v $PG_VERSION | sort -r | head -n1 | cut -d'/' -f5)
        if [[ -n ${PG_OLD_VERSION} ]]; then
          echo -e "${red}‣ Migrating PostgreSQL ${PG_OLD_VERSION} data to ${PG_VERSION}...${reset}"

          # protect the existing data from being altered by apt-get
          mv ${PG_HOME}/${PG_OLD_VERSION} ${PG_HOME}/${PG_OLD_VERSION}.migrating

          echo -e "${red}‣ Installing PostgreSQL ${PG_OLD_VERSION}...${reset}"
          if ! ( apt-get update &&  DEBIAN_FRONTEND=noninteractive apt-get install -y postgresql-${PG_OLD_VERSION} postgresql-client-${PG_OLD_VERSION} ) >/dev/null; then
            echo "ERROR! Failed to install PostgreSQL ${PG_OLD_VERSION}. Exiting..."
            # first move the old data back
            rm -rf ${PG_HOME}/${PG_OLD_VERSION}
            mv ${PG_HOME}/${PG_OLD_VERSION}.migrating ${PG_HOME}/${PG_OLD_VERSION}
            exit 1
          fi
          rm -rf /var/lib/apt/lists/*

          # we're ready to migrate, move back the old data and remove the trap
          rm -rf ${PG_HOME}/${PG_OLD_VERSION}
          mv ${PG_HOME}/${PG_OLD_VERSION}.migrating ${PG_HOME}/${PG_OLD_VERSION}
        fi

        if [[ -n $PG_PASSWORD ]]; then
          echo "${PG_PASSWORD}" > /tmp/pwfile
        fi

        exec_as_postgres ${PG_BINDIR}/initdb --pgdata=${PG_DATADIR} \
          --username=${PG_USER} \
          --encoding=unicode \
          --auth=trust ${PG_PASSWORD:+--pwfile=/tmp/pwfile} ${POSTGRES_INITDB_ARGS} >/dev/null

        if [[ -n ${PG_OLD_VERSION} ]]; then
          PG_OLD_BINDIR=/usr/lib/postgresql/${PG_OLD_VERSION}/bin
          PG_OLD_DATADIR=${PG_HOME}/${PG_OLD_VERSION}/main
          PG_OLD_CONF=${PG_OLD_DATADIR}/postgresql.conf
          PG_OLD_HBA_CONF=${PG_OLD_DATADIR}/pg_hba.conf
          PG_OLD_IDENT_CONF=${PG_OLD_DATADIR}/pg_ident.conf

          echo -n "‣ Migration in progress. Please be patient..."
          exec_as_postgres ${PG_BINDIR}/pg_upgrade \
            -b ${PG_OLD_BINDIR} -B ${PG_BINDIR} \
            -d ${PG_OLD_DATADIR} -D ${PG_DATADIR} \
            -o "-c config_file=${PG_OLD_CONF} --hba_file=${PG_OLD_HBA_CONF} --ident_file=${PG_OLD_IDENT_CONF}" \
            -O "-c config_file=${PG_CONF} --hba_file=${PG_HBA_CONF} --ident_file=${PG_IDENT_CONF}"
          echo
        fi
        ;;
    esac

    configure_hot_standby
    configure_log_archiving

    # Change DSM from `posix' to `sysv' if we are inside an lx-brand container
    if [[ $(uname -v) == "BrandZ virtual linux" ]]; then
      set_postgresql_param "dynamic_shared_memory_type" "sysv"
    fi
  fi

  # configure path to data_directory
  set_postgresql_param "data_directory" "${PG_DATADIR}"

  # configure logging
  set_postgresql_param "log_directory" "${PG_LOGDIR}"
  set_postgresql_param "log_filename" "postgresql-${PG_VERSION}-main.log"

  # trust connections from local network
  if [[ ${PG_TRUST_LOCALNET} == true ]]; then
    echo "Trusting connections from the local network..."
    set_hba_param "host all all samenet trust"
  fi

  # allow remote connections to postgresql database
  set_hba_param "host all all 0.0.0.0/0 md5"
}

set_resolvconf_perms() {
  echo "Setting resolv.conf ACLs..."
  setfacl -m user:${PG_USER}:r /etc/resolv.conf || true
}

configure_recovery() {
  if [[ ${REPLICATION_MODE} == slave ]]; then
    echo "Configuring recovery..."
    if [[ ! -f ${PG_RECOVERY_CONF} ]]; then
      # initialize recovery.conf on the firstrun (slave only)
      exec_as_postgres touch ${PG_RECOVERY_CONF}
      ( echo "standby_mode = 'on'";
        echo "primary_conninfo = 'host=${REPLICATION_HOST} port=${REPLICATION_PORT} user=${REPLICATION_USER} password=${REPLICATION_PASS} sslmode=${REPLICATION_SSLMODE}'";
      ) > ${PG_RECOVERY_CONF}
    else
      set_recovery_param "host"      "${REPLICATION_HOST}"
      set_recovery_param "port"      "${REPLICATION_PORT}"
      set_recovery_param "user"      "${REPLICATION_USER}"
      set_recovery_param "password"  "${REPLICATION_PASS}"    "true"
      set_recovery_param "sslmode"   "${REPLICATION_SSLMODE}"
    fi
  else
    # recovery.conf can only exist on a slave node, its existence otherwise causes problems
    rm -rf ${PG_RECOVERY_CONF}
  fi
}

create_user() {
  if [[ -n ${DB_USER} ]]; then
    case $REPLICATION_MODE in
      slave|snapshot|backup)
        echo "INFO! Database user cannot be created on a $REPLICATION_MODE node. Skipping..."
        ;;
      *)
        if [[ -z ${DB_PASS} ]]; then
          echo "ERROR! Please specify a password for DB_USER in DB_PASS. Exiting..."
          exit 1
        fi
        db_users=($(awk -F'[, ]' '{for (i = 1 ; i <= NF ; i++) print $i}' <<< "${DB_USER}"))
        if [[ ${#db_users[@]} == 1 ]]; then
          # Support old-style syntax, so that passwords with spaces still work
          if [[ -z $(psql -U ${PG_USER} -Atc "SELECT 1 FROM pg_catalog.pg_user WHERE usename = '${DB_USER}'";) ]]; then
            echo -e "${yellow}‣ Creating database user (legacy): ${yellow_bold}${DB_USER}${reset}"
            psql -U ${PG_USER} -c "CREATE ROLE \"${DB_USER}\" with LOGIN CREATEDB PASSWORD '${DB_PASS}';" >/dev/null
          else
            echo -e "${yellow}‣ Database user already exists, will not create: ${yellow_bold}${DB_USER}${reset}"
          fi
        else
          db_passwords=($(awk -F' ' '{for (i = 1 ; i <= NF ; i++) print $i}' <<< "${DB_PASS}"))
          i=0
          for db_user in "${db_users[@]}"; do
            password_index=$(( $i % ${#db_passwords[@]} ))
            db_password="${db_users[$password_index]}"
            if [[ -z $(psql -U ${PG_USER} -Atc "SELECT 1 FROM pg_catalog.pg_user WHERE usename = '${db_user}'";) ]]; then
              echo -e "${yellow}‣ Creating database user: ${yellow_bold}${db_user}${yellow}, pass index ${yellow_bold}${password_index}${reset}"
              psql -U ${PG_USER} -c "CREATE ROLE \"${db_user}\" with LOGIN CREATEDB PASSWORD '${DB_PASS}';" >/dev/null
            else
              echo -e "${yellow}‣ Database user already exists, will not create: ${yellow_bold}${db_user}${reset}"
            fi
            i=$(($i+1))
          done
        fi
        ;;
    esac
  fi
}

load_extensions() {
  local database=${1?missing argument}

  if [[ ${DB_UNACCENT} == true ]]; then
    echo
    echo "WARNING: "
    echo "  The DB_UNACCENT option will be deprecated in favour of DB_EXTENSION soon."
    echo "  Please migrate to using DB_EXTENSION=\"unaccent\""
    echo
    echo -e "${yellow}‣ Loading unaccent extension...${reset}"
    psql -U ${PG_USER} -d ${database} -c "CREATE EXTENSION IF NOT EXISTS unaccent;" >/dev/null 2>&1
  fi

  for extension in $(awk -F'[, ]' '{for (i = 1 ; i <= NF ; i++) print $i}' <<< "${DB_EXTENSION}"); do
    echo -e "${yellow}‣ Loading ${yellow_bold}${extension}${yellow} extension...${reset}"
    psql -U ${PG_USER} -d ${database} -c "CREATE EXTENSION IF NOT EXISTS \"${extension}\";" >/dev/null 2>&1
  done
}

create_database() {
  if [[ -n ${DB_NAME} ]]; then
    case $REPLICATION_MODE in
      slave|snapshot|backup)
        echo "INFO! Database cannot be created on a $REPLICATION_MODE node. Skipping..."
        ;;
      *)
        for database in $(awk -F'[, ]+' '{for (i = 1 ; i <= NF ; i++) print $i}' <<< "${DB_NAME}"); do
          db_user="${DB_USER}"
          if [[ $database = *"@"* ]]; then
            db_user=$(echo $database | cut -d@ -f1)
            database=$(echo $database | cut -d@ -f2)
          else
            db_user=$(awk -F'[, ]' '{ print $1 }' <<< "${DB_USER}")
          fi

          echo -e "${yellow}‣ Creating database: ${yellow_bold}${database}${reset}"
          if [[ -z $(psql -U ${PG_USER} -Atc "SELECT 1 FROM pg_catalog.pg_database WHERE datname = '${database}'";) ]]; then
            psql -U ${PG_USER} -c "CREATE DATABASE \"${database}\" WITH TEMPLATE = \"${DB_TEMPLATE}\";" >/dev/null
          fi

          load_extensions ${database}

          if [[ -n ${db_user} ]]; then
            echo -e "${yellow}‣ Granting access to ${yellow_bold}${database}${reset}${yellow} for user ${yellow_bold}${db_user}${reset}${yellow}...${reset}"
            psql -U ${PG_USER} -c "GRANT ALL PRIVILEGES ON DATABASE \"${database}\" to \"${db_user}\";" >/dev/null
          fi
        done
        ;;
    esac
  fi
}

create_replication_user() {
  if [[ -n ${REPLICATION_USER} ]]; then
    case $REPLICATION_MODE in
      slave|snapshot|backup) ;; # replication user can only be created on the master
      *)
        if [[ -z ${REPLICATION_PASS} ]]; then
          echo "ERROR! Please specify a password for REPLICATION_USER in REPLICATION_PASS. Exiting..."
          exit 1
        fi

        echo -e "${yellow}‣ Creating replication user: ${yellow_bold}${REPLICATION_USER}${reset}"
        if [[ -z $(psql -U ${PG_USER} -Atc "SELECT 1 FROM pg_catalog.pg_user WHERE usename = '${REPLICATION_USER}'";) ]]; then
          psql -U ${PG_USER} -c "CREATE ROLE \"${REPLICATION_USER}\" WITH REPLICATION LOGIN ENCRYPTED PASSWORD '${REPLICATION_PASS}';" >/dev/null
        fi

        set_hba_param "host replication ${REPLICATION_USER} 0.0.0.0/0 md5"
        ;;
    esac
  fi
}

start_postgres() {
  echo -e "${orange}‣ Starting PostgreSQL ${PG_VERSION}: ${yellow_bold}${PG_BINDIR}postgres -D \"${PG_DATADIR}\" ${EXTRA_ARGS}${reset}"
  exec su-exec ${PG_USER} ${PG_BINDIR}/postgres -D "${PG_DATADIR}" ${EXTRA_ARGS}
}

start_postgres_daemon() {
  # internal start of server in order to allow set-up using psql-client
  # does not listen on TCP/IP and waits until start finishes
  echo -e "${orange}‣ Starting PostgreSQL ${PG_VERSION}: ${yellow_bold}pg_ctl -D $PG_DATADIR -o "${EXTRA_ARGS} -c listen_addresses=''" -w start${reset}"
  su-exec ${PG_USER} pg_ctl -D "$PG_DATADIR" -o "${EXTRA_ARGS} -c listen_addresses=''" -w start
}

stop_postgres_daemon() {
  # Stop the daemon
  echo -e "${orange}‣ Stoppping PostgreSQL...${reset}"
  su-exec ${PG_USER} pg_ctl -D "$PG_DATADIR" -s -m fast -w stop
}


run_startup_scripts() {
  # Run scripts in much the same manner that the official image does
  if [ -f /docker-entrypoint-initdb.d/* ]; then

    : ${PG_USER:=postgres}
    : ${PG_DATABASE:=$PG_USER}
    export PG_USER PG_DATABASE

    for f in /docker-entrypoint-initdb.d/*; do
      case "$f" in
        *.sh)
          echo -e "${yellow}$0: running ${yellow_bold}$f${reset}"
          . "$f"
          ;;
        *.sql)
          echo -e "${yellow}$0: executing ${yellow_bold}$f${reset}"
          psql -v ON_ERROR_STOP=1 --username "$PG_USER" --dbname "$PG_DATABASE" < "$f"
          echo
          ;;
        *)
          echo -e "${orange}$0: ignoring ${yellow_bold}$f${reset}"
          ;;
        esac
    echo
    done

  fi
}

configure_postgresql() {
  initialize_database
  configure_recovery
  configure_ssl

  # start postgres server internally for the creation of users and databases
  rm -rf ${PG_DATADIR}/postmaster.pid
  start_postgres_daemon

  create_user
  create_database
  create_replication_user

  run_startup_scripts

  # stop the postgres server
  stop_postgres_daemon

}
