# This is a new configuration for CircleCI 2.0
version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    working_directory: /root/postgresql
    steps:
      - checkout
      - restore_cache:
          key: docker-binary-17.03.0-ce
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            if ! command docker version >/dev/null 2>&1; then
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/local/bin
            fi
      - save_cache:
          key: docker-binary-17.03.0-ce
          paths:
            - "/usr/local/bin"
      - run:
          name: Build image
          command: |
            IMAGE_NAME=boky/postgresql ./hooks/build
      - run:
          name: Test image
          command: |
            docker run -d --name=postgresql boky/postgresql &&
            (max=30; echo -n "Waiting for Postgres to be healthy... "; i=0; until docker ps -a | grep -q healthy; do i=$((i+1)); if [[ $i == $max ]]; then exit 1; fi; sleep 1; echo -n "$i "; done;)
